apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

configMapGenerator:
  - name: nginx-config
    behavior: replace
    files:
      - nginx.conf

patches:
  - path: patch-service.yaml
  - path: patch-frontend.yaml

replicas:
  - name: backend
    count: 2
