apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-api
  template:
    metadata:
      labels:
        app: db-api
    spec:
      containers:
      - name: db-api
        image: manu144/db-api:v1
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: db-host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: db-name
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: db-api
spec:
  selector:
    app: db-api
  ports:
  - port: 8000
