apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml
  - init-sql-configmap.yaml
  - backend-deploy.yaml
  - backend-v2-deploy.yaml
  - frontend-deploy.yaml
  - frontend-v2-deploy.yaml
  - db-api.yaml

configMapGenerator:
  - name: backend-code
    files:
      - server.js
  - name: frontend-html
    files:
      - index.html
  - name: frontend-html-v3
    files:
      - index-v3.html
  - name: frontend-html-prod
    files:
      - index-prod.html
  - name: nginx-config
    files:
      - nginx.conf

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: db-secret
    literals:
      - password=password123
