name: Deploy to K8s

on:
  push:
    branches:
      - master

jobs:
  deploy-dev:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to Dev
        run: |
          kubectl apply -k overlays/dev
          kubectl rollout status deployment/backend -n dev --timeout=60s
          kubectl rollout status deployment/frontend -n dev --timeout=60s
